services:
  python-3.9.19-bookworm-patched:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    userns_mode: host
    command: bash
    volumes:
      - ./repro:/root/project
